export type BienesInmueblesFormValues = {
  operation: string;
  dateFilter: string;
  registroNumero: string;
  registroVolumen: string;
  registroSeccion: string;
  registroFecha: string;
  escriturasNumero: string;
  escriturasNotaria: string;
  escriturasFecha: string;
  boletinNumero: string;
  boletinVolumen: string;
  boletinFecha: string;
  convenioNumero: string;
  convenioVolumen: string;
  convenioFecha: string;
  nombre: string;
  antecedente: string;
  colony: string;
  street: string;
  block: string;
  lot: string;
  totalArea: string;
  builtArea: string;
  cadastralValue: string;
  commercialValue: string;
  latitude: string;
  longitude: string;
};

export type BienesInmueblesTableRow = BienesInmueblesFormValues & {
  id: string;
  clave: string;
  descripcion: string;
  ubicacion: string;
  estado: "Activo" | "Inactivo";
  fecha: string;
  responsable: string;
  apiId?: number;
  rppNumber?: string;
  cNumber?: string;
  inventoryStatus?: "active" | "maintenance" | "baja";
  operationTypeId?: number;
  operationTypeName?: string;
};
